"""
JSON-backed cache for validated SiteConfig objects, keyed by listing_url.

Once a config has been generated by Grok and confirmed against the live site
(see validate_site_config in process_site.py), it's saved here so subsequent
runs skip the Firecrawl scrape + Grok call entirely.
"""

import json
from pathlib import Path
from typing import Optional

from site_config import SiteConfig

CACHE_PATH = Path(__file__).parent / "site_configs_cache.json"


def load_cached_config(listing_url: str) -> Optional[SiteConfig]:
    if not CACHE_PATH.exists():
        return None
    try:
        data = json.loads(CACHE_PATH.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return None

    entry = data.get(listing_url)
    if not entry:
        return None

    try:
        return SiteConfig(**entry)
    except TypeError:
        # Cached entry doesn't match the current SiteConfig shape (e.g. after a
        # field was added/removed) — treat as a miss rather than crashing.
        return None


def save_config_to_cache(config: SiteConfig) -> None:
    data = {}
    if CACHE_PATH.exists():
        try:
            data = json.loads(CACHE_PATH.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            data = {}

    data[config.listing_url] = config._asdict()
    CACHE_PATH.write_text(json.dumps(data, indent=2), encoding="utf-8")


def clear_cache(listing_url: Optional[str] = None) -> None:
    """Clear the whole cache, or just one entry if listing_url is given."""
    if not CACHE_PATH.exists():
        return
    if listing_url is None:
        CACHE_PATH.unlink()
        return
    try:
        data = json.loads(CACHE_PATH.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return
    data.pop(listing_url, None)
    CACHE_PATH.write_text(json.dumps(data, indent=2), encoding="utf-8")
